#include "Output.h"

#include "Commands.h"

namespace Skeltn { namespace Commands {
	void help(int argc, char **argv) {
		Out << "Skeltn is a tool meant for easing the development of C and C++ projects by providing a straightfoward way to set up a working build process.\n\n";
		Out << "There are several commands that you will likely want to use:\n\n";
		
		Out <<
		"$ " << YellowText << "skeltn init [Project Name]" << End << ": initializes an empty project that skeltn can build. Creates a 'src' directory, an 'include' directory, a basic 'Main.cpp' and a '.skeltn' file that specifies build parameters.\n\n"
		<<
		"$ " << YellowText << "skeltn build" << End << ": builds the project in the current directory. Requires the presence of a '.skeltn' file, and may fail if you haven't set up your build environment.\n\n"
		<<
		"$ " << YellowText << "skeltn clean" << End << ": cleans the project directory.\n\n"
		<<
		"$ " << YellowText << "skeltn link add" << End << ": adds the current directory as a path the compiler will search for link libraries.\n\n"
		<<
		"$ " << YellowText << "skeltn include add" << End << ": adds the current directory as a path the compiler will search for include directories.\n\n";
		
		Out << "To learn how to actually write a '.skeltn' file, consult the documentation--although the file generated by 'skeltn init' is probably enough to get a project working.\n";
	}
} }